import { createServiceClient, corsHeaders, handleCors, successResponse, errorResponse } from "../_shared/supabase-client.ts";
import { extractOGImage } from "../_shared/og-image.ts";
import { recordHeartbeat } from "../_shared/heartbeat.ts";

// A truncated headline ending in a stray initial — "for the B.",
// "criticized U.", "the U." — signals the source title was clipped
// by Google CSE's preview machinery. The underlying content can still
// be relevant, but a truncated title makes the signal hard to triage
// without the full article. We DON'T reject these (the content may
// matter); we DO log them so we can tune later if they're noisy.
function looksTruncated(title: string | null | undefined): boolean {
  if (!title) return false;
  // Trailing single capital letter + period (e.g. "for the B.")
  if (/\s[A-Z]\.\s*$/.test(title)) return true;
  // Trailing "the X." pattern
  if (/\bthe\s+[A-Z]\.\s*$/.test(title)) return true;
  return false;
}

// Hosts where Google CSE's "title" field is unreliable — the page has
// no meaningful <title> for an article (it's a video/reel/shorts page),
// so Google synthesizes one from page metadata or content extraction
// (often AI-generated by the host or by Google itself). The snippet
// remains the verifiable extraction, but the title can be fabricated
// prose that doesn't match the underlying media. May 10 2026: a
// pension-fund signal was traced to an Instagram reel where the
// "title" was a confidently-stated paragraph of background context
// the reel itself didn't say. We now distrust titles from these hosts
// and ingest the snippet alone.
function isSuspiciousTitleHost(sourceUrl: string | null | undefined): boolean {
  if (!sourceUrl) return false;
  return /(?:^|\.)(?:instagram\.com|tiktok\.com|youtube\.com\/shorts|facebook\.com\/reel|threads\.net)/i.test(sourceUrl);
}

// Title-vs-snippet token overlap. When the title is editorial framing
// that doesn't appear in the actual page content, the overlap is near
// zero. Used as a secondary check on hosts where titles are usually
// reliable but might have been tampered. Returns true if at least 25%
// of the title's content tokens (≥4 chars) appear in the snippet.
function titleOverlapsSnippet(title: string, snippet: string): boolean {
  const STOP = new Set(['the','and','for','with','this','that','from','have','were','will','been','their','about','says','just','what','when','where','why','how','more','most','than','then','they','those','these','some','only','also','into']);
  const tokens = (title.toLowerCase().match(/[a-z][a-z0-9'-]{3,}/g) ?? [])
    .filter(t => !STOP.has(t));
  if (tokens.length < 3) return true; // too short to judge — pass through
  const hay = snippet.toLowerCase();
  const hits = tokens.filter(t => hay.includes(t)).length;
  return hits / tokens.length >= 0.25;
}

Deno.serve(async (req) => {
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  const supabase = createServiceClient();

  const googleApiKey = Deno.env.get('GOOGLE_SEARCH_API_KEY');
  const googleEngineId = Deno.env.get('GOOGLE_SEARCH_ENGINE_ID');

  // Create monitoring history entry
  const { data: historyEntry } = await supabase
    .from('monitoring_history')
    .insert({
      source_name: 'Google News API',
      status: 'running',
      scan_metadata: { method: 'google_custom_search' }
    })
    .select()
    .single();

  try {
    console.log('Starting Google News API monitoring scan...');

    // 2026-05-08: write heartbeat at the START. With 70+ keyword queries
    // per run (29 Petronas + 43 BCCH client keywords), this function
    // routinely exceeds the 150s edge-function execution limit and gets
    // killed before reaching the end-of-function heartbeat at line 278.
    // The Monitor Health panel was showing 3-day staleness despite the
    // function actually firing every hour — heartbeat was the missing
    // signal. Writing 'running' here gives operators visibility even if
    // the run gets cut short.
    await recordHeartbeat(supabase, 'monitor-news-google-hourly', 'running', { phase: 'started' });

    if (!googleApiKey || !googleEngineId) {
      console.warn('Google Search API not configured - using fallback RSS method');
      
      await supabase
        .from('monitoring_history')
        .update({
          status: 'completed',
          scan_completed_at: new Date().toISOString(),
          error_message: 'Google Search API not configured',
          signals_created: 0
        })
        .eq('id', historyEntry?.id);

      return successResponse({ 
        success: false, 
        error: 'Google Search API not configured',
        fallback: 'Use monitor-news for RSS-based fallback'
      });
    }

    // Get all clients with monitoring keywords + negative-keyword
    // config. Negative keywords are appended to every Google CSE
    // query for that client as `-term` exclusions, pushing out
    // content matching unwanted scope (e.g. Petronas's Malaysian
    // HQ news for the Petronas Canada client). Stored on
    // clients.monitoring_config.negative_keywords as a JSON array
    // of strings.
    const { data: clients, error: clientsError } = await supabase
      .from('clients')
      .select('id, name, industry, monitoring_keywords, monitoring_config, tactic_keywords');

    if (clientsError) throw clientsError;

    // Fetch actively monitored person entities per client
    const { data: monitoredEntities } = await supabase
      .from('entities')
      .select('id, name, client_id, attributes')
      .eq('active_monitoring_enabled', true)
      .eq('type', 'person');

    // Build map: client_id → person entity names
    const clientPersonsMap = new Map<string, string[]>();
    for (const e of monitoredEntities || []) {
      if (!e.client_id) continue;
      const list = clientPersonsMap.get(e.client_id) || [];
      list.push(e.name);
      clientPersonsMap.set(e.client_id, list);
    }

    console.log(`Found ${clients?.length || 0} clients to monitor`);

    let signalsCreated = 0;
    let itemsScanned = 0;
    const searchResults: any[] = [];

    // Build search queries for each client
    for (const client of clients || []) {
      const queries: string[] = [];

      // Build the negative-keyword suffix once per client. Each
      // configured negative keyword is appended as a `-term` Google
      // CSE exclusion — pushes out content scoped against unwanted
      // geography or topics. For Petronas Canada this excludes the
      // Malaysian HQ content (Sabah, Sarawak, Bintulu, RGT-3, FSRU,
      // Kuala Lumpur, Bursa Malaysia, etc.) that was leaking into
      // the Canadian feed via global "Petronas" keyword matches.
      // Multi-word negatives are wrapped in quotes so they match as
      // a phrase rather than exclude every article containing any
      // of the words separately.
      const negativeKeywords: string[] = Array.isArray(client.monitoring_config?.negative_keywords)
        ? client.monitoring_config.negative_keywords.filter((k: any) => typeof k === 'string' && k.trim().length > 0)
        : [];
      const negSuffix = negativeKeywords
        .map((k) => (k.includes(' ') ? `-"${k}"` : `-${k}`))
        .join(' ');
      const withNeg = (q: string) => negSuffix ? `${q} ${negSuffix}` : q;

      // Add client name as primary query
      queries.push(withNeg(`"${client.name}" security OR threat OR incident`));
      queries.push(withNeg(`"${client.name}" protest OR activist OR opposition`));

      // Add monitoring keywords — always scoped to Canadian geography
      // to avoid matching unrelated global use of broad terms like
      // "LNG". The bare "BC" token is intentionally NOT in the scope
      // — Google CSE matches it to too many false positives ("B.C.
      // Smith" bylines, building codes, etc.) which let Malaysian
      // Petronas content through during May 2026 audit. Use the full
      // "British Columbia" string only.
      //
      // 2026-05-07: removed .slice(0, 3) cap. With it, 26 of Petronas's
      // 29 keywords (Wet'suwet'en, Gidimt'en, Coastal GasLink, Stand.earth,
      // pipeline protest BC, etc.) were never reaching Google News API —
      // 30-day reality probe returned 0 hits for any of those terms.
      // 2026-05-10: keyword queries now lean toward security-relevant
      // angles. Previously each keyword fired a single broad "$KW Canada
      // OR BC news" query that returned almost entirely corporate /
      // business news (LNG export deals, FID announcements, capex
      // updates) which the relevance gate then correctly rejected as
      // not-security-relevant. Net yield was ~1 admit per 50 scanned.
      // Now each keyword fires TWO scoped queries — one for direct
      // security angles, one for activist/protest angles — so the gate
      // sees more material it can plausibly admit.
      // NGO/advocacy keywords get paired with operational asset terms
      // instead of kinetic-verb gates. Reason: an environmental org
      // saying "expanded LNG Canada would put climate targets out of
      // reach" is operationally significant on its own — no protest /
      // blockade / threat verb required. Verb-gated queries silently
      // dropped this class of signal (discovered 2026-05-11 when a
      // Stand.Earth / Liz McDowell quote was missing from the feed).
      //
      // Per-client list lives on clients.monitoring_config.ngo_keywords.
      const ngoKeywords: string[] = Array.isArray(client.monitoring_config?.ngo_keywords)
        ? client.monitoring_config.ngo_keywords.filter((k: any) => typeof k === 'string' && k.trim().length >= 3)
        : [];
      const ngoSet = new Set(ngoKeywords.map(k => k.toLowerCase()));

      // Asset-style keywords: everything in monitoring_keywords that
      // isn't an NGO. These are the operational targets we pair NGO
      // mentions against.
      const assetKeywords: string[] = (client.monitoring_keywords ?? [])
        .filter((k: string) => typeof k === 'string' && !ngoSet.has(k.toLowerCase()));

      if (client.monitoring_keywords?.length > 0) {
        for (const keyword of client.monitoring_keywords) {
          if (ngoSet.has(keyword.toLowerCase())) {
            // NGO/advocacy angle — fire one query that pairs the NGO
            // name with operational assets. Captures commentary,
            // critiques, statements, campaign launches without
            // requiring kinetic verbiage. Cap the OR clause to the
            // first 10 asset keywords to stay under Google CSE query
            // length limits.
            const assetTerms = assetKeywords.slice(0, 10).map(a => `"${a}"`).join(' OR ');
            if (assetTerms) {
              queries.push(withNeg(`"${keyword}" (${assetTerms})`));
            } else {
              // Fallback if client has no non-NGO keywords yet.
              queries.push(withNeg(`"${keyword}" Canada OR "British Columbia"`));
            }
          } else {
            // Security / incident angle — threats, sabotage, regulatory action.
            queries.push(withNeg(`"${keyword}" Canada OR "British Columbia" (threat OR incident OR sabotage OR investigation OR ruling OR injunction OR breach OR opposition)`));
            // Activist / protest angle — direct action against the asset.
            queries.push(withNeg(`"${keyword}" Canada OR "British Columbia" (protest OR blockade OR activist OR "land defender" OR "direct action" OR boycott OR divest)`));
          }
        }
      }

      // 2026-05-10: tactic terms moved to per-client clients.tactic_keywords.
      // The previous hardcoded TACTIC_TERMS list mixed Petronas oil/gas
      // protest tactics with BCCH gender-clinic protest tactics — fine
      // for those two clients, useless for any future client onboarded
      // (a tech company, retailer, etc.) without code edits. Now each
      // client's threat-domain tactics are queried only against that
      // client. Onboarding client #3 = populate clients.tactic_keywords,
      // no deploy.
      const tacticKeywords: string[] = Array.isArray((client as any).tactic_keywords)
        ? (client as any).tactic_keywords.filter((t: any) => typeof t === 'string' && t.trim().length >= 4)
        : [];
      for (const tactic of tacticKeywords) {
        queries.push(withNeg(`"${tactic}" Canada OR "British Columbia"`));
      }

      // Add person entity name queries — searches for staff/VIPs by name
      // in news and activist contexts. These are the queries most likely to
      // surface targeted coverage, threats, or protest activity.
      //
      // Cap at 25 per cron run to bound API cost, but ROTATE the starting
      // index so over a few hours every monitored person gets queried, not
      // just the first 25. Petronas has 46 active_monitoring entities (most
      // of them persons) — without rotation, the same 6 would get queried
      // every hour and the other 40+ would never produce coverage.
      const PERSON_QUERY_CAP = 25;
      const allPersonNames = clientPersonsMap.get(client.id) || [];
      // Step by a co-prime-ish stride so consecutive hours visit different
      // entities; over 24h every entity gets multiple queries.
      const offset = allPersonNames.length > 0
        ? (new Date().getUTCHours() * 7) % allPersonNames.length
        : 0;
      const namesThisRun: string[] = [];
      for (let i = 0; i < Math.min(PERSON_QUERY_CAP, allPersonNames.length); i++) {
        namesThisRun.push(allPersonNames[(offset + i) % allPersonNames.length]);
      }
      for (const name of namesThisRun) {
        queries.push(withNeg(`"${name}" news OR threat OR protest OR harassment OR controversy`));
      }
      console.log(`[news-google] ${client.name}: ${namesThisRun.length}/${allPersonNames.length} person-name queries (offset ${offset})`);

      // Execute Google Custom Search for each query
      for (const query of queries) {
        try {
          const searchUrl = new URL('https://www.googleapis.com/customsearch/v1');
          searchUrl.searchParams.set('key', googleApiKey);
          searchUrl.searchParams.set('cx', googleEngineId);
          searchUrl.searchParams.set('q', query);
          searchUrl.searchParams.set('num', '5');
          searchUrl.searchParams.set('dateRestrict', 'd3'); // Last 3 days
          searchUrl.searchParams.set('sort', 'date');

          console.log(`Searching: ${query}`);
          
          const response = await fetch(searchUrl.toString());
          
          if (!response.ok) {
            const errorText = await response.text();
            console.error(`Google Search API error: ${response.status} - ${errorText}`);
            continue;
          }

          const data = await response.json();
          itemsScanned += data.items?.length || 0;

          for (const item of data.items || []) {
            // Skip results with no meaningful snippet
            const snippet = (item.snippet || '').trim();
            if (snippet.length < 40) continue;

            // 2026-05-08 source-fidelity guard: require title or snippet to
            // contain at least one client-specific token. Google CSE
            // sometimes returns tangentially-matched articles where the
            // search term appears only in metadata, not the article body.
            // The LLM then hallucinates rich prose from background knowledge.
            const clientTokens = (client.monitoring_keywords || [])
              .filter((k: string) => typeof k === 'string' && k.trim().length >= 3)
              .map((k: string) => k.toLowerCase());
            if (clientTokens.length > 0) {
              const haystack = `${item.title || ''} ${snippet}`.toLowerCase();
              const matched = clientTokens.some((tok: string) => haystack.includes(tok));
              if (!matched) {
                console.log(`[news-google] dropping no-token-match: ${item.title?.substring(0, 80)}`);
                continue;
              }
            }

            // Note truncated titles for telemetry — content is still
            // ingested (it may be operationally relevant) but we log
            // the marker so we can revisit if these prove noisy.
            if (looksTruncated(item.title)) {
              console.log(`[news-google] truncated-title marker on: ${item.title?.substring(0, 80)}`);
            }

            // Antifabrication guard: drop the title from signalText
            // when the source host is known to produce unreliable
            // titles (Instagram reels etc.) OR when the title doesn't
            // share any meaningful tokens with the snippet — both are
            // strong indicators the title is editorialized/fabricated
            // background that the snippet (the actual page extract)
            // doesn't support. Snippet-only ingestion preserves the
            // verifiable evidence and lets the relevance gate decide.
            const titleSuspicious =
              isSuspiciousTitleHost(item.link) ||
              !titleOverlapsSnippet(item.title || '', snippet);
            if (titleSuspicious) {
              console.log(`[news-google] title-suspicious; ingesting snippet only: ${(item.title || '').substring(0, 80)} | url=${item.link}`);
            }
            const signalText = titleSuspicious ? snippet : `${item.title}\n\n${snippet}`;

            // Extract OG image from article page (non-blocking)
            const imageUrl = item.link ? await extractOGImage(item.link).catch(() => null) : null;

            // Pull the article's actual publish time from Google CSE
            // pagemap.metatags. This becomes the surface_date in ingest-
            // signal's staleness gate (replaces the brittle AI-extracted
            // event_date that mis-tagged fresh articles about old events).
            const meta = (item.pagemap?.metatags?.[0] ?? {}) as Record<string, string>;
            const articlePublishedTime =
              meta['article:published_time']
              ?? meta['og:article:published_time']
              ?? meta['date']
              ?? meta['pubdate']
              ?? null;

            // Route through ingest-signal for PECL classification, relevance gate, and dedup
            const ingestResult = await supabase.functions.invoke('ingest-signal', {
              body: {
                text: signalText,
                source_url: item.link || null,
                image_url: imageUrl || undefined,
                client_id: client.id,
                source_key: 'Google News API',
                raw_json: {
                  source: 'google_news_api',
                  source_url: item.link,
                  snippet,
                  display_link: item.displayLink,
                  search_query: query,
                  matched_client: client.name,
                  article_published_time: articlePublishedTime,
                  // Provenance: capture the original title separately
                  // even when discarded, so an audit can reconstruct
                  // why the signal text doesn't match the source page.
                  source_title: item.title ?? null,
                  title_discarded: titleSuspicious,
                  title_discarded_reason: titleSuspicious
                    ? (isSuspiciousTitleHost(item.link)
                        ? 'suspicious_host'
                        : 'low_title_snippet_overlap')
                    : null,
                },
              },
            });

            if (ingestResult.error) {
              console.error(`ingest-signal error for "${item.title?.substring(0, 50)}":`, ingestResult.error);
              continue;
            }

            const ingestData = ingestResult.data as any;
            const ingestStatus = ingestData?.status || 'unknown';

            if (ingestStatus === 'rejected' || ingestStatus === 'suppressed' || ingestStatus === 'filed_as_update') {
              console.log(`↳ ${ingestStatus}: ${item.title?.substring(0, 50)}... (${ingestData?.reason || ingestData?.detail || ''})`);
              continue;
            }

            if (ingestData?.signal_id || ingestStatus === 'enqueued' || ingestStatus === 'critical_processed') {
              signalsCreated++;
              console.log(`✓ Created signal for ${client.name}: ${item.title?.substring(0, 60)}...`);
              searchResults.push({
                client: client.name,
                title: item.title,
                url: item.link,
                status: ingestStatus,
              });
            }
          }

          // Rate limit: wait between requests
          await new Promise(resolve => setTimeout(resolve, 200));

        } catch (queryError) {
          console.error(`Error processing query "${query}":`, queryError);
        }
      }
    }

    // Update monitoring history
    await supabase
      .from('monitoring_history')
      .update({
        status: 'completed',
        scan_completed_at: new Date().toISOString(),
        items_scanned: itemsScanned,
        signals_created: signalsCreated,
        scan_metadata: {
          method: 'google_custom_search',
          clients_monitored: clients?.length || 0,
          results_sample: searchResults.slice(0, 10)
        }
      })
      .eq('id', historyEntry?.id);

    // Heartbeat
  await recordHeartbeat(supabase, 'monitor-news-google-hourly', 'completed', { items_scanned: itemsScanned, signals_created: signalsCreated });

  console.log(`Google News monitoring complete. Scanned ${itemsScanned} items, created ${signalsCreated} signals.`);

    return successResponse({
      success: true,
      items_scanned: itemsScanned,
      signals_created: signalsCreated,
      clients_monitored: clients?.length || 0,
      sample_results: searchResults.slice(0, 5)
    });

  } catch (error) {
    console.error('Google News monitoring error:', error);
    
    const errorMessage = error instanceof Error ? error.message : String(error);
    
    await supabase
      .from('monitoring_history')
      .update({
        status: 'failed',
        scan_completed_at: new Date().toISOString(),
        error_message: errorMessage
      })
      .eq('id', historyEntry?.id);

    return errorResponse(errorMessage, 500);
  }
});
