import { createServiceClient, corsHeaders, handleCors, successResponse, errorResponse } from "../_shared/supabase-client.ts";
import { extractOGImage } from "../_shared/og-image.ts";
import { startHeartbeat, completeHeartbeat, failHeartbeat, getLatestSucceededResultSummary } from "../_shared/heartbeat.ts";
import { cleanSignalExcerpt } from "../_shared/signal-text.ts";
import { getTenantNewsAllowlist, extractHost, isAllowedDomain } from "../_shared/news-domain-allowlist.ts";

// PROD-S Track G (2026-05-23) — cap forensic `filtered_signals` inserts per
// tenant per cycle to avoid write amplification on junk-volume spikes.
// Aggregate rejection counts continue (in result_summary), so the
// observability denominator is preserved.
const TRACK_G_FILTERED_INSERT_CAP_PER_TENANT_PER_CYCLE = 10;

// A truncated headline ending in a stray initial — "for the B.",
// "criticized U.", "the U." — signals the source title was clipped
// by Google CSE's preview machinery. The underlying content can still
// be relevant, but a truncated title makes the signal hard to triage
// without the full article. We DON'T reject these (the content may
// matter); we DO log them so we can tune later if they're noisy.
function looksTruncated(title: string | null | undefined): boolean {
  if (!title) return false;
  // Trailing single capital letter + period (e.g. "for the B.")
  if (/\s[A-Z]\.\s*$/.test(title)) return true;
  // Trailing "the X." pattern
  if (/\bthe\s+[A-Z]\.\s*$/.test(title)) return true;
  return false;
}

// Hosts where Google CSE's "title" field is unreliable — the page has
// no meaningful <title> for an article (it's a video/reel/shorts page),
// so Google synthesizes one from page metadata or content extraction
// (often AI-generated by the host or by Google itself). The snippet
// remains the verifiable extraction, but the title can be fabricated
// prose that doesn't match the underlying media. May 10 2026: a
// pension-fund signal was traced to an Instagram reel where the
// "title" was a confidently-stated paragraph of background context
// the reel itself didn't say. We now distrust titles from these hosts
// and ingest the snippet alone.
function isSuspiciousTitleHost(sourceUrl: string | null | undefined): boolean {
  if (!sourceUrl) return false;
  return /(?:^|\.)(?:instagram\.com|tiktok\.com|youtube\.com\/shorts|facebook\.com\/reel|threads\.net)/i.test(sourceUrl);
}

// Title-vs-snippet token overlap. When the title is editorial framing
// that doesn't appear in the actual page content, the overlap is near
// zero. Used as a secondary check on hosts where titles are usually
// reliable but might have been tampered. Returns true if at least 25%
// of the title's content tokens (≥4 chars) appear in the snippet.
function titleOverlapsSnippet(title: string, snippet: string): boolean {
  const STOP = new Set(['the','and','for','with','this','that','from','have','were','will','been','their','about','says','just','what','when','where','why','how','more','most','than','then','they','those','these','some','only','also','into']);
  const tokens = (title.toLowerCase().match(/[a-z][a-z0-9'-]{3,}/g) ?? [])
    .filter(t => !STOP.has(t));
  if (tokens.length < 3) return true; // too short to judge — pass through
  const hay = snippet.toLowerCase();
  const hits = tokens.filter(t => hay.includes(t)).length;
  return hits / tokens.length >= 0.25;
}

Deno.serve(async (req) => {
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  const supabase = createServiceClient();

  const googleApiKey = Deno.env.get('GOOGLE_SEARCH_API_KEY');
  const googleEngineId = Deno.env.get('GOOGLE_SEARCH_ENGINE_ID');

  // Create monitoring history entry
  const { data: historyEntry } = await supabase
    .from('monitoring_history')
    .insert({
      source_name: 'Google News API',
      status: 'running',
      scan_metadata: { method: 'google_custom_search' }
    })
    .select()
    .single();

  // PROD-G — deterministic self-budgeting (hotfix granularity rev).
  //
  // First cut (initial PROD-G) checked budget only BETWEEN clients. On prod
  // workloads (PECL has 29 keywords × 2 angles = 58 queries; BCCH has 43 × 2
  // = 86) a single client can consume >100s internally before the inter-
  // client budget check next fires. Result: platform SIGKILL at 150s before
  // any clean exit. Row stuck in status='running' forever — same pathology
  // the budget was meant to fix.
  //
  // Hotfix: check budget BEFORE each query (inside the inner loop), not just
  // between clients. Cursor granularity is (client_id, query_index) so resume
  // picks up at the exact next un-attempted query within the same client.
  //
  // Also: reap stale 'running' heartbeats from prior SIGKILLed runs so the
  // table doesn't accumulate forever-pending rows. Only rows older than the
  // platform kill ceiling + 30s buffer qualify — a younger row could be a
  // legitimately concurrent run (pg_cron may overlap if a run is still
  // executing at the next tick), so we won't touch it.
  //
  // Heartbeat hoisted above the try so the catch block below can call
  // failHeartbeat on the same handle — otherwise a thrown error during
  // the scan would leave the row stuck in status='running' indefinitely.
  const STARTED_AT = Date.now();
  const BUDGET_MS = 105_000; // 45s margin under platform 150s kill
  const JOB_NAME = 'monitor-news-google-hourly';

  // Stale heartbeat recovery. Threshold = 180s = (150s platform kill) + 30s
  // safety buffer. Anything older than this cannot still be executing
  // (platform would have killed it). Conditional on status='running' so we
  // never clobber a 'succeeded' or 'failed' row. Atomic + race-safe even
  // if a second invocation overlaps — both UPDATEs target the same row but
  // the operation is idempotent (same fields, same outcome).
  const STALE_HEARTBEAT_THRESHOLD_MS = 180_000;
  try {
    const staleBefore = new Date(Date.now() - STALE_HEARTBEAT_THRESHOLD_MS).toISOString();
    const { data: reaped } = await supabase
      .from('cron_heartbeat')
      .update({
        status: 'failed',
        completed_at: new Date().toISOString(),
        error_message: 'Heartbeat reaped by next invocation — prior run never completed (likely 150s platform SIGKILL or process crash before failHeartbeat could fire)',
        result_summary: { error: 'stale_running_reaped', reaped_at: new Date().toISOString() },
      })
      .eq('job_name', JOB_NAME)
      .eq('status', 'running')
      .lt('started_at', staleBefore)
      .select('id');
    if (reaped && reaped.length > 0) {
      console.log(`[monitor-news-google] Reaped ${reaped.length} stale running heartbeat row(s) older than ${STALE_HEARTBEAT_THRESHOLD_MS}ms`);
    }
  } catch (e) {
    console.warn(`[monitor-news-google] stale-heartbeat reap failed (non-fatal):`, e);
  }

  // Read cursor BEFORE writing this run's heartbeat so the read can never
  // return our own in-flight row. Filters status='succeeded' to skip
  // failed/in-flight prior runs that may not carry a meaningful cursor.
  // Cursor shape: { client_id: string, query_index: number }. We also
  // tolerate the legacy bare-string shape from the initial PROD-G deploy
  // (treat as client_id with query_index=0) so the first invocation after
  // hotfix doesn't lose work — though in practice no legacy cursor ever
  // landed because the old code got SIGKILLed before writing one.
  const priorSummary = await getLatestSucceededResultSummary(supabase, JOB_NAME);
  const rawCursor: unknown = (priorSummary as any)?.next_cursor ?? null;
  let resumeCursor: { client_id: string; query_index: number } | null = null;
  if (typeof rawCursor === 'string' && rawCursor) {
    resumeCursor = { client_id: rawCursor, query_index: 0 };
  } else if (rawCursor && typeof rawCursor === 'object' && (rawCursor as any).client_id) {
    resumeCursor = {
      client_id: String((rawCursor as any).client_id),
      query_index: Number((rawCursor as any).query_index) || 0,
    };
  }

  const hb = await startHeartbeat(supabase, JOB_NAME);

  try {
    console.log('Starting Google News API monitoring scan...');

    if (!googleApiKey || !googleEngineId) {
      console.warn('Google Search API not configured - using fallback RSS method');
      
      await supabase
        .from('monitoring_history')
        .update({
          status: 'completed',
          scan_completed_at: new Date().toISOString(),
          error_message: 'Google Search API not configured',
          signals_created: 0
        })
        .eq('id', historyEntry?.id);

      return successResponse({ 
        success: false, 
        error: 'Google Search API not configured',
        fallback: 'Use monitor-news for RSS-based fallback'
      });
    }

    // Get all clients with monitoring keywords + negative-keyword
    // config. Negative keywords are appended to every Google CSE
    // query for that client as `-term` exclusions, pushing out
    // content matching unwanted scope (e.g. Petronas's Malaysian
    // HQ news for the Petronas Canada client). Stored on
    // clients.monitoring_config.negative_keywords as a JSON array
    // of strings.
    // status='active' only. Inactive clients are fixtures (benchmark,
    // QA) that don't belong in real-time monitoring rotations. Without
    // this filter, _benchmark_petronas (inactive, identical keywords
    // to Petronas Canada, sorts alphabetically first) won every
    // content_hash dedup race and absorbed ~80% of real signals.
    // PROD-G: explicit ORDER BY id for cursor semantics. The cursor stores
    // a client_id; the next run resumes from the client immediately after
    // that id, which only works if order is stable across runs.
    const { data: clients, error: clientsError } = await supabase
      .from('clients')
      .select('id, name, tenant_id, industry, monitoring_keywords, monitoring_config, tactic_keywords')
      .eq('status', 'active')
      .order('id', { ascending: true });

    if (clientsError) throw clientsError;

    // Fetch actively monitored person entities per client
    const { data: monitoredEntities } = await supabase
      .from('entities')
      .select('id, name, client_id, attributes')
      .eq('active_monitoring_enabled', true)
      .eq('type', 'person');

    // Build map: client_id → person entity names
    const clientPersonsMap = new Map<string, string[]>();
    for (const e of monitoredEntities || []) {
      if (!e.client_id) continue;
      const list = clientPersonsMap.get(e.client_id) || [];
      list.push(e.name);
      clientPersonsMap.set(e.client_id, list);
    }

    console.log(`Found ${clients?.length || 0} clients to monitor`);

    // PROD-G cursor: resume from the client AT resumeCursor.client_id (inclusive),
    // and within THAT client, from query index resumeCursor.query_index. If the
    // cursor refers to a client removed/deactivated since the last run, fall
    // back to index 0 with a warn log (not silent) and reset query_index too.
    // startQueryIdx0 applies ONLY to the first iterated client — every
    // subsequent client starts at query 0 of its own queries array.
    const totalClients = clients?.length ?? 0;
    let startIdx = 0;
    let startQueryIdx0 = 0;
    if (resumeCursor) {
      const idx = (clients ?? []).findIndex((c: any) => c.id === resumeCursor!.client_id);
      if (idx >= 0) {
        startIdx = idx;
        startQueryIdx0 = resumeCursor.query_index;
      } else {
        console.warn(`[monitor-news-google] resume cursor client ${resumeCursor.client_id} not in active client list (renamed/deactivated?); restarting from index 0`);
      }
    }
    console.log(`[monitor-news-google] resuming at clientIdx=${startIdx}/${totalClients}, queryIdx=${startQueryIdx0} (cursor=${resumeCursor ? `${resumeCursor.client_id}@q${resumeCursor.query_index}` : '<none>'})`);

    let signalsCreated = 0;
    let itemsScanned = 0;
    const searchResults: any[] = [];
    let partialExit = false;
    let nextCursor: { client_id: string; query_index: number } | null = null;
    let processedCount = 0;
    let stopIdx = totalClients;

    // PROD-S Track G (2026-05-23) — per-tenant aggregate stats for the
    // allowlist enforcement pass. Watchdog reads from result_summary.
    // track_g_per_tenant.<tenant_id> to detect 100% rejection over
    // consecutive cycles.
    const trackGPerTenant: Record<string, {
      urls_received: number;
      urls_rejected_domain: number;
      urls_passed_allowlist: number;
      overlay_failed: boolean;
      used_overlay: boolean;
      allowlist_size: number;
    }> = {};

    // Build search queries for each client. Labeled outer loop so the
    // inner per-query budget check can break out of BOTH loops cleanly
    // when it trips mid-client.
    clientLoop:
    for (let clientIdx = startIdx; clientIdx < totalClients; clientIdx++) {
      // Inter-client budget check (cheap path — skip the whole next client
      // before building its queries array if we already have no time).
      if (Date.now() - STARTED_AT >= BUDGET_MS) {
        partialExit = true;
        nextCursor = { client_id: (clients as any)![clientIdx].id, query_index: 0 };
        stopIdx = clientIdx;
        console.log(`[monitor-news-google] budget exhausted between clients at ${clientIdx}/${totalClients}; next run resumes at ${nextCursor.client_id}@q0`);
        break;
      }
      const client = (clients as any)![clientIdx];

      // PROD-S Track G (2026-05-23) — resolve per-tenant news-domain allowlist
      // ONCE per client iteration. Effective allowlist = GLOBAL_NEWS_BASELINE
      // ∪ tenants.settings.news_domain_allowlist overlay. Failure mode: helper
      // falls back to baseline-only with overlay_failed=true; we surface that
      // in telemetry but never silently admit everything or skip the tenant.
      const allowlistResolution = await getTenantNewsAllowlist(supabase, client.tenant_id);
      const cycleStats = {
        urls_received: 0,
        urls_rejected_domain: 0,
        urls_passed_allowlist: 0,
        filtered_signals_inserted: 0,
      };
      if (allowlistResolution.overlay_failed) {
        console.warn(`[Track G] tenant=${client.tenant_id} overlay lookup failed; using GLOBAL_NEWS_BASELINE only (size=${allowlistResolution.allowlist.size})`);
      }

      const queries: string[] = [];

      // Build the negative-keyword suffix once per client. Each
      // configured negative keyword is appended as a `-term` Google
      // CSE exclusion — pushes out content scoped against unwanted
      // geography or topics. For Petronas Canada this excludes the
      // Malaysian HQ content (Sabah, Sarawak, Bintulu, RGT-3, FSRU,
      // Kuala Lumpur, Bursa Malaysia, etc.) that was leaking into
      // the Canadian feed via global "Petronas" keyword matches.
      // Multi-word negatives are wrapped in quotes so they match as
      // a phrase rather than exclude every article containing any
      // of the words separately.
      const negativeKeywords: string[] = Array.isArray(client.monitoring_config?.negative_keywords)
        ? client.monitoring_config.negative_keywords.filter((k: any) => typeof k === 'string' && k.trim().length > 0)
        : [];
      const negSuffix = negativeKeywords
        .map((k) => (k.includes(' ') ? `-"${k}"` : `-${k}`))
        .join(' ');
      const withNeg = (q: string) => negSuffix ? `${q} ${negSuffix}` : q;

      // Add client name as primary query
      queries.push(withNeg(`"${client.name}" security OR threat OR incident`));
      queries.push(withNeg(`"${client.name}" protest OR activist OR opposition`));

      // Add monitoring keywords — always scoped to Canadian geography
      // to avoid matching unrelated global use of broad terms like
      // "LNG". The bare "BC" token is intentionally NOT in the scope
      // — Google CSE matches it to too many false positives ("B.C.
      // Smith" bylines, building codes, etc.) which let Malaysian
      // Petronas content through during May 2026 audit. Use the full
      // "British Columbia" string only.
      //
      // 2026-05-07: removed .slice(0, 3) cap. With it, 26 of Petronas's
      // 29 keywords (Wet'suwet'en, Gidimt'en, Coastal GasLink, Stand.earth,
      // pipeline protest BC, etc.) were never reaching Google News API —
      // 30-day reality probe returned 0 hits for any of those terms.
      // 2026-05-10: keyword queries now lean toward security-relevant
      // angles. Previously each keyword fired a single broad "$KW Canada
      // OR BC news" query that returned almost entirely corporate /
      // business news (LNG export deals, FID announcements, capex
      // updates) which the relevance gate then correctly rejected as
      // not-security-relevant. Net yield was ~1 admit per 50 scanned.
      // Now each keyword fires TWO scoped queries — one for direct
      // security angles, one for activist/protest angles — so the gate
      // sees more material it can plausibly admit.
      // NGO/advocacy keywords get paired with operational asset terms
      // instead of kinetic-verb gates. Reason: an environmental org
      // saying "expanded LNG Canada would put climate targets out of
      // reach" is operationally significant on its own — no protest /
      // blockade / threat verb required. Verb-gated queries silently
      // dropped this class of signal (discovered 2026-05-11 when a
      // Stand.Earth / Liz McDowell quote was missing from the feed).
      //
      // Per-client list lives on clients.monitoring_config.ngo_keywords.
      const ngoKeywords: string[] = Array.isArray(client.monitoring_config?.ngo_keywords)
        ? client.monitoring_config.ngo_keywords.filter((k: any) => typeof k === 'string' && k.trim().length >= 3)
        : [];
      const ngoSet = new Set(ngoKeywords.map(k => k.toLowerCase()));

      // Asset-style keywords: everything in monitoring_keywords that
      // isn't an NGO. These are the operational targets we pair NGO
      // mentions against.
      const assetKeywords: string[] = (client.monitoring_keywords ?? [])
        .filter((k: string) => typeof k === 'string' && !ngoSet.has(k.toLowerCase()));

      if (client.monitoring_keywords?.length > 0) {
        for (const keyword of client.monitoring_keywords) {
          if (ngoSet.has(keyword.toLowerCase())) {
            // NGO/advocacy angle — fire one query that pairs the NGO
            // name with operational assets. Captures commentary,
            // critiques, statements, campaign launches without
            // requiring kinetic verbiage. Cap the OR clause to the
            // first 10 asset keywords to stay under Google CSE query
            // length limits.
            const assetTerms = assetKeywords.slice(0, 10).map(a => `"${a}"`).join(' OR ');
            if (assetTerms) {
              queries.push(withNeg(`"${keyword}" (${assetTerms})`));
            } else {
              // Fallback if client has no non-NGO keywords yet.
              queries.push(withNeg(`"${keyword}" Canada OR "British Columbia"`));
            }
          } else {
            // Security / incident angle — threats, sabotage, regulatory action.
            queries.push(withNeg(`"${keyword}" Canada OR "British Columbia" (threat OR incident OR sabotage OR investigation OR ruling OR injunction OR breach OR opposition)`));
            // Activist / protest angle — direct action against the asset.
            queries.push(withNeg(`"${keyword}" Canada OR "British Columbia" (protest OR blockade OR activist OR "land defender" OR "direct action" OR boycott OR divest)`));
          }
        }
      }

      // 2026-05-10: tactic terms moved to per-client clients.tactic_keywords.
      // The previous hardcoded TACTIC_TERMS list mixed Petronas oil/gas
      // protest tactics with BCCH gender-clinic protest tactics — fine
      // for those two clients, useless for any future client onboarded
      // (a tech company, retailer, etc.) without code edits. Now each
      // client's threat-domain tactics are queried only against that
      // client. Onboarding client #3 = populate clients.tactic_keywords,
      // no deploy.
      const tacticKeywords: string[] = Array.isArray((client as any).tactic_keywords)
        ? (client as any).tactic_keywords.filter((t: any) => typeof t === 'string' && t.trim().length >= 4)
        : [];
      for (const tactic of tacticKeywords) {
        queries.push(withNeg(`"${tactic}" Canada OR "British Columbia"`));
      }

      // Add person entity name queries — searches for staff/VIPs by name
      // in news and activist contexts. These are the queries most likely to
      // surface targeted coverage, threats, or protest activity.
      //
      // Cap at 25 per cron run to bound API cost, but ROTATE the starting
      // index so over a few hours every monitored person gets queried, not
      // just the first 25. Petronas has 46 active_monitoring entities (most
      // of them persons) — without rotation, the same 6 would get queried
      // every hour and the other 40+ would never produce coverage.
      const PERSON_QUERY_CAP = 25;
      const allPersonNames = clientPersonsMap.get(client.id) || [];
      // Step by a co-prime-ish stride so consecutive hours visit different
      // entities; over 24h every entity gets multiple queries.
      const offset = allPersonNames.length > 0
        ? (new Date().getUTCHours() * 7) % allPersonNames.length
        : 0;
      const namesThisRun: string[] = [];
      for (let i = 0; i < Math.min(PERSON_QUERY_CAP, allPersonNames.length); i++) {
        namesThisRun.push(allPersonNames[(offset + i) % allPersonNames.length]);
      }
      for (const name of namesThisRun) {
        queries.push(withNeg(`"${name}" news OR threat OR protest OR harassment OR controversy`));
      }
      console.log(`[news-google] ${client.name}: ${namesThisRun.length}/${allPersonNames.length} person-name queries (offset ${offset})`);

      // Resume position WITHIN this client. Only the first iterated client
      // honors startQueryIdx0 (the cursor). Every subsequent client iterates
      // its full queries array from 0.
      const startQueryIdx = (clientIdx === startIdx) ? startQueryIdx0 : 0;

      // Execute Google Custom Search for each query
      for (let qIdx = startQueryIdx; qIdx < queries.length; qIdx++) {
        // PROD-G hotfix: per-query budget check. Without this, one
        // high-keyword client (PECL 58 queries × ~700ms = ~40s; BCCH
        // 86 queries × ~700ms = ~60s, both with rate-limit sleep on
        // top) could blow past the budget while still inside its
        // inner loop, never reaching the inter-client check at the
        // top of clientLoop. Inner-loop check ensures we can exit
        // cleanly mid-client and resume at the exact next query.
        if (Date.now() - STARTED_AT >= BUDGET_MS) {
          partialExit = true;
          nextCursor = { client_id: client.id, query_index: qIdx };
          stopIdx = clientIdx;
          console.log(`[monitor-news-google] budget exhausted mid-client at ${clientIdx}/${totalClients}, queryIdx=${qIdx}/${queries.length}; next run resumes at ${nextCursor.client_id}@q${nextCursor.query_index}`);
          break clientLoop;
        }
        const query = queries[qIdx];
        try {
          const searchUrl = new URL('https://www.googleapis.com/customsearch/v1');
          searchUrl.searchParams.set('key', googleApiKey);
          searchUrl.searchParams.set('cx', googleEngineId);
          searchUrl.searchParams.set('q', query);
          searchUrl.searchParams.set('num', '5');
          searchUrl.searchParams.set('dateRestrict', 'd3'); // Last 3 days
          searchUrl.searchParams.set('sort', 'date');

          console.log(`Searching: ${query}`);
          
          const response = await fetch(searchUrl.toString());
          
          if (!response.ok) {
            const errorText = await response.text();
            console.error(`Google Search API error: ${response.status} - ${errorText}`);
            continue;
          }

          const data = await response.json();
          itemsScanned += data.items?.length || 0;

          for (const item of data.items || []) {
            // Skip results with no meaningful snippet. cleanSignalExcerpt
            // strips Google CSE artefacts (relative-time preludes like
            // "1 day ago …", chained ellipses, trailing "- Facebook"
            // attributions) so downstream — including the auto-generated
            // signal title — sees clean prose, not raw search previews.
            const snippet = cleanSignalExcerpt(item.snippet);
            if (snippet.length < 40) continue;

            // 2026-05-08 source-fidelity guard: require title or snippet to
            // contain at least one client-specific token. Google CSE
            // sometimes returns tangentially-matched articles where the
            // search term appears only in metadata, not the article body.
            // The LLM then hallucinates rich prose from background knowledge.
            const clientTokens = (client.monitoring_keywords || [])
              .filter((k: string) => typeof k === 'string' && k.trim().length >= 3)
              .map((k: string) => k.toLowerCase());
            if (clientTokens.length > 0) {
              const haystack = `${item.title || ''} ${snippet}`.toLowerCase();
              const matched = clientTokens.some((tok: string) => haystack.includes(tok));
              if (!matched) {
                console.log(`[news-google] dropping no-token-match: ${item.title?.substring(0, 80)}`);
                continue;
              }
            }

            // Note truncated titles for telemetry — content is still
            // ingested (it may be operationally relevant) but we log
            // the marker so we can revisit if these prove noisy.
            if (looksTruncated(item.title)) {
              console.log(`[news-google] truncated-title marker on: ${item.title?.substring(0, 80)}`);
            }

            // Antifabrication guard: drop the title from signalText
            // when the source host is known to produce unreliable
            // titles (Instagram reels etc.) OR when the title doesn't
            // share any meaningful tokens with the snippet — both are
            // strong indicators the title is editorialized/fabricated
            // background that the snippet (the actual page extract)
            // doesn't support. Snippet-only ingestion preserves the
            // verifiable evidence and lets the relevance gate decide.
            const titleSuspicious =
              isSuspiciousTitleHost(item.link) ||
              !titleOverlapsSnippet(item.title || '', snippet);
            if (titleSuspicious) {
              console.log(`[news-google] title-suspicious; ingesting snippet only: ${(item.title || '').substring(0, 80)} | url=${item.link}`);
            }
            const cleanTitle = cleanSignalExcerpt(item.title);
            const signalText = titleSuspicious ? snippet : `${cleanTitle}\n\n${snippet}`;

            // Extract OG image from article page (non-blocking)
            const imageUrl = item.link ? await extractOGImage(item.link).catch(() => null) : null;

            // Pull the article's actual publish time from Google CSE
            // pagemap.metatags. This becomes the surface_date in ingest-
            // signal's staleness gate (replaces the brittle AI-extracted
            // event_date that mis-tagged fresh articles about old events).
            const meta = (item.pagemap?.metatags?.[0] ?? {}) as Record<string, string>;
            const articlePublishedTime =
              meta['article:published_time']
              ?? meta['og:article:published_time']
              ?? meta['date']
              ?? meta['pubdate']
              ?? null;

            // PROD-S Track G (2026-05-23) — pre-ingest domain allowlist enforcement.
            // Reject URLs whose host is not in the tenant's effective allowlist
            // (baseline ∪ overlay) BEFORE ingest-signal is invoked. Saves
            // AI-gate cost, telemetry pollution, and analyst-feed noise.
            cycleStats.urls_received += 1;
            const candidateHost = extractHost(item.link);
            if (!isAllowedDomain(candidateHost, allowlistResolution.allowlist)) {
              cycleStats.urls_rejected_domain += 1;
              // Cap forensic inserts per tenant per cycle. Aggregate counts
              // continue in cycleStats so the observability denominator is
              // preserved even if we stop writing rows.
              if (cycleStats.filtered_signals_inserted < TRACK_G_FILTERED_INSERT_CAP_PER_TENANT_PER_CYCLE) {
                cycleStats.filtered_signals_inserted += 1;
                supabase.from('filtered_signals').insert({
                  raw_text: (item.title || '').substring(0, 500),
                  source_url: item.link || null,
                  source_name: 'monitor-news-google',
                  client_id: client.id,
                  filter_reason: 'source_domain_not_allowlisted',
                  relevance_score: null,
                  relevance_reason: `host=${candidateHost ?? '(unparseable)'} not in tenant allowlist (size=${allowlistResolution.allowlist.size}, used_overlay=${allowlistResolution.used_overlay})`,
                }).then(() => {}).catch(() => {});
              }
              continue;
            }
            cycleStats.urls_passed_allowlist += 1;

            // Route through ingest-signal for PECL classification, relevance gate, and dedup
            const ingestResult = await supabase.functions.invoke('ingest-signal', {
              body: {
                text: signalText,
                source_url: item.link || null,
                image_url: imageUrl || undefined,
                client_id: client.id,
                source_key: 'Google News API',
                raw_json: {
                  source: 'google_news_api',
                  source_url: item.link,
                  snippet,
                  display_link: item.displayLink,
                  search_query: query,
                  matched_client: client.name,
                  article_published_time: articlePublishedTime,
                  // Provenance: capture the original title separately
                  // even when discarded, so an audit can reconstruct
                  // why the signal text doesn't match the source page.
                  source_title: item.title ?? null,
                  title_discarded: titleSuspicious,
                  title_discarded_reason: titleSuspicious
                    ? (isSuspiciousTitleHost(item.link)
                        ? 'suspicious_host'
                        : 'low_title_snippet_overlap')
                    : null,
                },
              },
            });

            if (ingestResult.error) {
              console.error(`ingest-signal error for "${item.title?.substring(0, 50)}":`, ingestResult.error);
              continue;
            }

            const ingestData = ingestResult.data as any;
            const ingestStatus = ingestData?.status || 'unknown';

            if (ingestStatus === 'rejected' || ingestStatus === 'suppressed' || ingestStatus === 'filed_as_update') {
              console.log(`↳ ${ingestStatus}: ${item.title?.substring(0, 50)}... (${ingestData?.reason || ingestData?.detail || ''})`);
              continue;
            }

            if (ingestData?.signal_id || ingestStatus === 'enqueued' || ingestStatus === 'critical_processed') {
              signalsCreated++;
              console.log(`✓ Created signal for ${client.name}: ${item.title?.substring(0, 60)}...`);
              searchResults.push({
                client: client.name,
                title: item.title,
                url: item.link,
                status: ingestStatus,
              });
            }
          }

          // Rate limit: wait between requests
          await new Promise(resolve => setTimeout(resolve, 200));

        } catch (queryError) {
          console.error(`Error processing query "${query}":`, queryError);
        }
      }

      // PROD-S Track G — fold this client's cycleStats into the per-tenant
      // aggregate. Same tenant across multiple clients accumulates. Watchdog
      // checks per-tenant rejection ratio against this object.
      {
        const t = client.tenant_id as string;
        const acc = trackGPerTenant[t] ?? {
          urls_received: 0,
          urls_rejected_domain: 0,
          urls_passed_allowlist: 0,
          overlay_failed: false,
          used_overlay: false,
          allowlist_size: allowlistResolution.allowlist.size,
        };
        acc.urls_received += cycleStats.urls_received;
        acc.urls_rejected_domain += cycleStats.urls_rejected_domain;
        acc.urls_passed_allowlist += cycleStats.urls_passed_allowlist;
        acc.overlay_failed = acc.overlay_failed || allowlistResolution.overlay_failed;
        acc.used_overlay = acc.used_overlay || allowlistResolution.used_overlay;
        acc.allowlist_size = allowlistResolution.allowlist.size;
        trackGPerTenant[t] = acc;
      }

      processedCount++;

      // Progress checkpoint: write incremental counts after each client.
      // The function frequently exceeded the 150s edge runtime limit and
      // got killed before reaching the final completeHeartbeat — the
      // budget exit above is the new primary safeguard, but this
      // checkpoint stays as a defense-in-depth telemetry surface (counts
      // remain visible mid-run rather than only at completion).
      //
      // Note: this write keeps status='running' on the in-flight row.
      // The cursor reader at the top of the function filters
      // status='succeeded', so these intermediate writes never get
      // picked up as a resume point — only completeHeartbeat below
      // advances the cursor for subsequent runs. Intentional.
      if (hb.id) {
        await supabase.from('cron_heartbeat')
          .update({ result_summary: { items_scanned: itemsScanned, signals_created: signalsCreated, phase: 'in_progress', processed_count: processedCount, total_clients: totalClients } })
          .eq('id', hb.id);
      }
    }

    // Update monitoring history
    await supabase
      .from('monitoring_history')
      .update({
        status: 'completed',
        scan_completed_at: new Date().toISOString(),
        items_scanned: itemsScanned,
        signals_created: signalsCreated,
        scan_metadata: {
          method: 'google_custom_search',
          clients_monitored: clients?.length || 0,
          results_sample: searchResults.slice(0, 10)
        }
      })
      .eq('id', historyEntry?.id);

    // Heartbeat — updates the row started at top of function so signals_created
    // reflects real yield. status='succeeded' regardless of partial flag; the
    // partial=true field is what the UI checks to badge the run as incomplete.
    // (Aaron's challenge: confirm downstream watchdog logic does not interpret
    // status='succeeded' partial exits as proof of full coverage. UI is gated
    // on result_summary.partial — see MonitorHealthPanel PARTIAL pill.)
    const elapsedMs = Date.now() - STARTED_AT;
    await completeHeartbeat(supabase, hb, {
      items_scanned: itemsScanned,
      signals_created: signalsCreated,
      partial: partialExit,
      next_cursor: nextCursor,                      // {client_id, query_index} | null
      started_at_cursor: resumeCursor,              // {client_id, query_index} | null — what THIS run resumed from
      start_idx: startIdx,
      start_query_idx: startQueryIdx0,
      stop_idx: stopIdx,
      total_clients: totalClients,
      processed_count: processedCount,
      budget_ms: BUDGET_MS,
      elapsed_ms: elapsedMs,
      // PROD-S Track G — per-tenant allowlist enforcement aggregate.
      // Watchdog rule `track_g_total_domain_rejection` reads from here.
      track_g_per_tenant: trackGPerTenant,
    });

    const cursorLabel = nextCursor ? `${nextCursor.client_id}@q${nextCursor.query_index}` : 'null';
    console.log(`Google News monitoring ${partialExit ? 'PARTIAL' : 'complete'}. Scanned ${itemsScanned} items, created ${signalsCreated} signals across ${processedCount}/${totalClients} clients in ${elapsedMs}ms.${partialExit ? ` Next run resumes at ${cursorLabel}.` : ''}`);

    return successResponse({
      success: true,
      partial: partialExit,
      next_cursor: nextCursor,
      items_scanned: itemsScanned,
      signals_created: signalsCreated,
      clients_monitored: totalClients,
      processed_count: processedCount,
      elapsed_ms: elapsedMs,
      sample_results: searchResults.slice(0, 5)
    });

  } catch (error) {
    console.error('Google News monitoring error:', error);

    const errorMessage = error instanceof Error ? error.message : String(error);

    // PROD-G: close out the heartbeat row in status='failed' instead of
    // leaving it stuck in 'running'. Without this, errors after the
    // startHeartbeat write produced the same hung-running pathology the
    // budget exit was meant to eliminate.
    await failHeartbeat(supabase, hb, error);

    await supabase
      .from('monitoring_history')
      .update({
        status: 'failed',
        scan_completed_at: new Date().toISOString(),
        error_message: errorMessage
      })
      .eq('id', historyEntry?.id);

    return errorResponse(errorMessage, 500);
  }
});
