import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { Resend } from 'https://esm.sh/resend@2.0.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

function generateSecurityAlertHTML(data: any): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #f6f9fc; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }
    .alert-box { background-color: #fee; border-left: 4px solid #dc2626; padding: 16px; margin: 24px; }
    .alert-level { color: #dc2626; font-size: 16px; font-weight: bold; margin: 0; }
    .section { padding: 0 24px; margin-bottom: 24px; }
    h1 { color: #1f2937; font-size: 32px; margin: 40px 24px; }
    h2 { color: #374151; font-size: 20px; margin-bottom: 12px; }
    p { color: #4b5563; font-size: 14px; line-height: 24px; }
    .label { color: #6b7280; font-size: 13px; }
    .value { color: #1f2937; font-weight: 600; }
    .button { background-color: #2563eb; color: white; text-decoration: none; padding: 12px 20px; border-radius: 6px; display: inline-block; margin: 24px; font-weight: bold; }
    .footer { color: #9ca3af; font-size: 12px; padding: 24px; }
    ul { list-style: none; padding-left: 0; }
    li { padding: 8px 0; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🚨 Security Alert</h1>
    
    <div class="alert-box">
      <p class="alert-level">Threat Level: ${data.threatLevel.toUpperCase()}</p>
    </div>

    <div class="section">
      <h2>Signal Details</h2>
      <p>${data.signalText}</p>
      <p class="label">Location: <span class="value">${data.location}</span></p>
      ${data.incidentId ? `<p class="label">Incident ID: <span class="value">${data.incidentId}</span></p>` : ''}
    </div>

    <div class="section">
      <h2>AI Analysis</h2>
      <p>${data.reasoning}</p>
    </div>

    ${data.containmentActions && data.containmentActions.length > 0 ? `
    <div class="section">
      <h2>Recommended Actions</h2>
      <ul>
        ${data.containmentActions.map((action: string, i: number) => `<li>${i + 1}. ${action}</li>`).join('')}
      </ul>
    </div>
    ` : ''}

    <a href="${data.dashboardUrl}" class="button">View in Dashboard</a>

    <p class="footer">
      This alert was automatically generated by the Autonomous SOC System.<br>
      Powered by AI-driven threat detection and response.
    </p>
  </div>
</body>
</html>
  `;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const resend = new Resend(Deno.env.get('RESEND_API_KEY') as string);

    console.log('Alert delivery: Processing pending alerts...');

    // Get pending alerts
    const { data: alerts, error: alertsError } = await supabase
      .from('alerts')
      .select('*, incidents(*)')
      .eq('status', 'pending')
      .limit(20);

    if (alertsError) throw alertsError;

    console.log(`Found ${alerts?.length || 0} pending alerts`);

    let delivered = 0;
    let failed = 0;

    for (const alert of alerts || []) {
      try {
        if (alert.channel === 'email') {
          // Extract email data from response_json
          const emailData = alert.response_json;
          
          // Generate HTML email
          const html = generateSecurityAlertHTML({
            threatLevel: emailData.threat_level || 'medium',
            signalText: emailData.body || 'Security alert',
            location: emailData.location || 'Unknown',
            reasoning: emailData.reasoning || '',
            containmentActions: emailData.containment_actions || [],
            incidentId: alert.incident_id,
            dashboardUrl: `${Deno.env.get('SUPABASE_URL')?.replace('supabase.co', 'lovable.app') || ''}`
          });

          // Send email via Resend
          const { error: sendError } = await resend.emails.send({
            from: 'Security Alert <alerts@resend.dev>',
            to: [alert.recipient],
            subject: emailData.subject || 'Security Alert',
            html,
          });

          if (sendError) {
            throw sendError;
          }

          console.log(`Email sent to ${alert.recipient}`);
        } else {
          // For non-email channels, just log
          console.log(`Alert channel ${alert.channel} not yet implemented`);
        }

        // Mark as sent
        const { error: updateError } = await supabase
          .from('alerts')
          .update({
            status: 'sent',
            sent_at: new Date().toISOString(),
            response_json: {
              ...alert.response_json,
              delivered_at: new Date().toISOString(),
              delivery_status: 'success'
            }
          })
          .eq('id', alert.id);

        if (!updateError) {
          delivered++;
        } else {
          failed++;
        }

      } catch (error) {
        console.error(`Error delivering alert ${alert.id}:`, error);
        
        // Mark as failed
        await supabase
          .from('alerts')
          .update({
            status: 'failed',
            response_json: {
              ...alert.response_json,
              error: error instanceof Error ? error.message : 'Unknown error',
              failed_at: new Date().toISOString()
            }
          })
          .eq('id', alert.id);
        
        failed++;
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        timestamp: new Date().toISOString(),
        summary: {
          total_alerts: alerts?.length || 0,
          delivered,
          failed
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in alert delivery:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
