import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Link,
  Preview,
  Section,
  Text,
} from 'npm:@react-email/components@0.0.22';
import * as React from 'npm:react@18.3.1';

interface SecurityAlertEmailProps {
  threatLevel: string;
  signalText: string;
  location: string;
  reasoning: string;
  containmentActions: string[];
  incidentId?: string;
  dashboardUrl: string;
}

export const SecurityAlertEmail = ({
  threatLevel,
  signalText,
  location,
  reasoning,
  containmentActions,
  incidentId,
  dashboardUrl,
}: SecurityAlertEmailProps) => (
  <Html>
    <Head />
    <Preview>Security Alert: {threatLevel.toUpperCase()} threat detected</Preview>
    <Body style={main}>
      <Container style={container}>
        <Heading style={h1}>🚨 Security Alert</Heading>
        
        <Section style={alertBox}>
          <Text style={alertLevel}>
            Threat Level: <strong>{threatLevel.toUpperCase()}</strong>
          </Text>
        </Section>

        <Section style={section}>
          <Heading style={h2}>Signal Details</Heading>
          <Text style={text}>{signalText}</Text>
          <Text style={label}>Location: <span style={value}>{location}</span></Text>
          {incidentId && (
            <Text style={label}>Incident ID: <span style={value}>{incidentId}</span></Text>
          )}
        </Section>

        <Section style={section}>
          <Heading style={h2}>AI Analysis</Heading>
          <Text style={text}>{reasoning}</Text>
        </Section>

        {containmentActions && containmentActions.length > 0 && (
          <Section style={section}>
            <Heading style={h2}>Recommended Actions</Heading>
            {containmentActions.map((action, i) => (
              <Text key={i} style={actionItem}>
                {i + 1}. {action}
              </Text>
            ))}
          </Section>
        )}

        <Section style={section}>
          <Link href={dashboardUrl} style={button}>
            View in Dashboard
          </Link>
        </Section>

        <Text style={footer}>
          This alert was automatically generated by the Autonomous SOC System.
          <br />
          Powered by AI-driven threat detection and response.
        </Text>
      </Container>
    </Body>
  </Html>
);

export default SecurityAlertEmail;

const main = {
  backgroundColor: '#f6f9fc',
  fontFamily:
    '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
  maxWidth: '600px',
};

const alertBox = {
  backgroundColor: '#fee',
  borderLeft: '4px solid #dc2626',
  padding: '16px',
  marginBottom: '24px',
};

const alertLevel = {
  color: '#dc2626',
  fontSize: '16px',
  fontWeight: 'bold',
  margin: '0',
};

const section = {
  padding: '0 48px',
  marginBottom: '24px',
};

const h1 = {
  color: '#1f2937',
  fontSize: '32px',
  fontWeight: 'bold',
  margin: '40px 0',
  padding: '0 48px',
};

const h2 = {
  color: '#374151',
  fontSize: '20px',
  fontWeight: 'bold',
  margin: '0 0 12px',
};

const text = {
  color: '#4b5563',
  fontSize: '14px',
  lineHeight: '24px',
  margin: '0 0 10px',
};

const label = {
  color: '#6b7280',
  fontSize: '13px',
  margin: '4px 0',
};

const value = {
  color: '#1f2937',
  fontWeight: '600',
};

const actionItem = {
  color: '#4b5563',
  fontSize: '14px',
  margin: '8px 0',
  paddingLeft: '8px',
};

const button = {
  backgroundColor: '#2563eb',
  borderRadius: '6px',
  color: '#fff',
  fontSize: '16px',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'block',
  padding: '12px 20px',
  fontWeight: 'bold',
};

const footer = {
  color: '#9ca3af',
  fontSize: '12px',
  lineHeight: '16px',
  padding: '0 48px',
  marginTop: '32px',
};
