-- WO-KILBACKS-HOUSEHOLD-CONFIG step 1 — ALIGNMENT ONLY.
-- CORRECTION (2026-08-10): public.client_geo_assets ALREADY EXISTS from WO-HAZARD-RELEVANCE Step 6
-- (migration 20260728130000_hazard_pathway_geometry.sql) as a PostGIS table:
--   (id, client_id, asset_name, asset_type, geom geometry(Geometry,4326), buffer_km, created_at),
-- with a gist(geom) index and RLS already enabled. This migration does NOT re-create it (the original
-- `create table if not exists` with a lat/lon shape was a no-op and has been removed to avoid a
-- migration file that describes a schema the live table does not have — DR/ledger parity).
--
-- Kilbacks household geometry (house/cabin/school) is DATA inserted into that existing table, not
-- schema — stored directly (env-specific, operator-confirmed coordinates), not via a repo migration.
--
-- The only durable schema effect here is a per-client btree index (the origin table has gist(geom)
-- but not necessarily a btree on client_id for client-scoped lookups).
create index if not exists client_geo_assets_client_idx on public.client_geo_assets(client_id);
