-- =============================================================================
-- Retroactive QA signal cleanup
-- Date: 2026-04-11
--
-- fortress-qa-agent was missing is_test: true before the April 11 fix.
-- This marks all signals generated by the QA cron (identifiable by the
-- [qa-{timestamp}] suffix in their text) as is_test = true, and closes
-- the incidents those signals spawned.
-- =============================================================================

-- 1. Mark all QA-generated signals as is_test = true
--    Pattern: raw_json->>'text' contains '[qa-' (fortress-qa-agent timestamp suffix)
UPDATE public.signals
SET
  is_test    = true,
  updated_at = NOW()
WHERE
  is_test IS DISTINCT FROM true
  AND (
    raw_json->>'text' ILIKE '%[qa-%'
    OR normalized_text ILIKE '%[qa-%'
  );

-- 2. Close any open incidents that were spawned from those test signals
UPDATE public.incidents i
SET
  status         = 'closed',
  resolved_at    = NOW(),
  updated_at     = NOW()
WHERE
  i.status NOT IN ('resolved', 'closed')
  AND EXISTS (
    SELECT 1 FROM public.signals s
    WHERE s.id = i.signal_id
      AND s.is_test = true
  );

-- 3. Also directly close incidents where title/summary contains qa-test indicators
UPDATE public.incidents
SET
  status      = 'closed',
  resolved_at = NOW(),
  updated_at  = NOW()
WHERE
  status NOT IN ('resolved', 'closed')
  AND is_test = true;
